### ISSUE TITLE
The google JWT is currently decoded with a call to google

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-server#26]
This is sub-optimal in many ways:
  - Additional time
  - Lower reliability
  - Not scalable in terms of load on google

We should really cache the google tokens locally and use a JWT decoding library instead.
That might also make it easier to switch to our own OAuth provider, if we so choose.

**Comment by shankari** [comment]
Instructions are at 
https://developers.google.com/accounts/docs/OpenIDConnect#validatinganidtoken

**Comment by shankari** [comment]
@jesca, if you are looking for an issue, this should be easier than the stats.py change, since for the stats.py change, I expect you to instrument the code first and then decide whether to make the change or not.

In this, you just need to implement something that is already documented somewhere. Given that the deadline is tomorrow morning, that might be an easier choice to finish in time.

**Comment by shankari** [comment]
Fixed by 0cd868a88361c7d02667fced624feba1641bff33

**Comment by shankari** [comment]
When I deployed this, I got the following error:
      File "api/cfc_webapp.py", line 368, in verifyUserToken
         tokenFields = oauth2client.client.verify_id_token(token,client_key)
      ...
      File "/home/ubuntu/anaconda/lib/python2.7/site-packages/oauth2client/crypt.py", line 190, in from_string
        'X509 certs are not supported by the PyCrypto library. '

Looking at the relevant source code, it looks like this is because this expects the pyopenssl library instead of the pycrypt library.
https://github.com/google/oauth2client/blob/master/oauth2client/client.py#L1515
    def verify_id_token(id_token, audience, http=None,
                                                   cert_uri=ID_TOKEN_VERIFICATION_CERTS):
        """Verifies a signed JWT id_token.
            This function requires PyOpenSSL and because of that it does not work on
            App Engine.


I tried testing with localhost with skipAuth = False so that the code would be triggered and got the same exception.

@jesca, any idea how this worked for you? Do you have pyopenssl installed by any chance?

**Comment by shankari** [comment]
after installing pyopenssl, I don't get the error, but the token is never validated and always falls back to the URL method, where it passes. So the token is clearly valid.

@jesca, did you actually see the token verification succeed? I assumed so and that you only explicitly documented the failure case in the pull request. Did you do additional setup to get it to work?

**Comment by jesca** [comment]
@shankari Just saw this message, let me go back to the code and see if I can figure out what's going on.

**Comment by shankari** [comment]
Just confirmed that the verification using the library fails when tested against the android emulator as well. The backup method of using the URL works.

**Comment by jesca** [comment]
Just confirmed that it is authenticating correctly using the oauth library (android emulator). 
![screen shot 2015-03-02 at 1 11 53 am](https://cloud.githubusercontent.com/assets/3870011/6437926/2318c5c0-c079-11e4-928e-ad99ec8572dc.png)

**Comment by jesca** [comment]
Did you run pip install requirements.txt (this was noted in the issue thread I believe) after merging the branch? There is a requirement that was added (the google-api-client)

**Comment by shankari** [comment]
Yes, I did run requirements.txt.
So the error that I get is not an import error for the oauth2 libraries, for during the actual authentication.

    2015-03-02 01:01:00,358:DEBUG:OAuth failed to verify id token, falling back to constructedURL

And if I add some additional logging for the backtrace, I get:

     Traceback (most recent call last):
       File "api/cfc_webapp.py", line 370, in verifyUserToken
         tokenFields = oauth2client.client.verify_id_token(token,client_key)
       File "/Users/shankari/OSS/anaconda/lib/python2.7/site-packages/oauth2client/util.py", line 128, in positional_wrapper
         return wrapped(*args, **kwargs)
       File "/Users/shankari/OSS/anaconda/lib/python2.7/site-packages/oauth2client/client.py", line 1012, in verify_id_token
         return crypt.verify_signed_jwt_with_certs(id_token, certs, audience)
       File "/Users/shankari/OSS/anaconda/lib/python2.7/site-packages/oauth2client/crypt.py", line 351, in verify_signed_jwt_with_certs
         raise AppIdentityError('Invalid token signature: %s' % jwt)

**Comment by shankari** [comment]
This is clearly a setup issue.

First, I had to install pyopenssl - otherwise I get the X509 error before.
Did you have to do so as well?
Are there other setup steps that you did? (I can try to reproduce them).

**Comment by shankari** [comment]
@jesca, you are off the hook - it works after all.

So it looks like putting this into requirements.txt is not sufficient.
When I installed the package through requirements.txt, it looks like it only installed the package, but not the dependencies.

When I uninstalled and then reinstalled the package manually using pip:
     $ pip uninstall google-api-python-client
     $ pip install --upgrade google-api-python-client

It installed a bunch of other dependencies:
     Installing collected packages: simplejson, rsa, pyasn1-modules, pyasn1, uritemplate, oauth2client, google-api-python-client

After which everything worked.

Will close this issue after updating the documentation....

**Comment by shankari** [comment]
So on the server, I did
  
  $ pip install --update -r requirements.txt

And it didn't appear to install the dependencies

  Collecting google-api-python-client==1.1 (from -r requirements.txt (line 10))
    Downloading google-api-python-client-1.1.tar.gz (71kB)
      100% |################################| 73kB 3.5MB/s 

Running pip manually did install all the extensions

  Installing collected packages: simplejson, rsa, pyasn1-modules, pyasn1, uritemplate, oauth2client, google-api-python-client

**Comment by jesca** [comment]
Glad that this is figured out. I didn't have to do any prior installation for pyopenssl. I only ran (sudo)  pip install - r requirements.txt. Does this pass on ios?

**Comment by shankari** [comment]
It wouldn't have because you weren't trying to decode with the ios client
key as well. I've made the changes locally though, and will test before
pushing. The server side is currently still always calling the URL decoder.
This was not the only issue that broke - I'll be sending out a pull request
with all the changes I had to make to get the tests to pass...

**Comment by shankari** [comment]
Working on the server now.

    2015-03-03 04:47:57,208:DEBUG:START POST /stats/set
    2015-03-03 04:47:57,208:DEBUG:Using OAuth2Client to verify id token from android phones
    2015-03-03 04:47:57,209:DEBUG:{u'aud': 

README has been updated with wrt ed2b9121cea463419917eaa053b406299d9be910
Closing this issue again.
