### ISSUE TITLE
Move away from br-fullpage to show the full page

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-server#281]
`br-fullpage` was an angular-based fullpage javascript library.
It _was_ at https://github.com/BjornRombaut/br-fullpage.git/, but it looks like it has been removed.
we either need to switch to a different fullpage library, or to a different set of style decisions altogether.

**Comment by shankari** [comment]
@sunil07t, adding this to your pile for now.

**Comment by shankari** [comment]
`br-fullpage` didn't work properly on firefox anyway.
Maybe a native angular/ionic solution will work better?

**Comment by shankari** [comment]
@sunil07t, can you revert my workaround by removing all references to br-fullpage and the checked in libraries?

Then, you can close this issue.

**Comment by sunil07t** [comment]
Sorry, I did not include closes #281 in my commit. Is there another way that I can close this issue?

**Comment by shankari** [comment]
You can just close it from the UI after I merge the pull request.

**Comment by shankari** [comment]
Fixed by @sunil07t
