### ISSUE TITLE
Handle out of memory issues in the webapp

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-server#322]
Today morning, `cfc_webapp` got a `MemoryError`.
I suspect that this is because the metrics and heatmap calculations allocate large amounts of memory, which are not deallocated when the API call completes, since the same python process is still running. Then, when @yw374cornell tried to retrieve all the data from the experiment, she allocated a bunch of more memory and that crashed the webapp.

**Comment by shankari** [comment]
First step is to get a watchdog in place that can restart if it fails. That should keep us limping along for now, before we decide whether we want to stick with bottle, or switch to something else like cherrypy or ???

**Comment by shankari** [comment]
@gtfierro, I know you have used watchdogs before. Any recommendations? I was going to try out supervisord (http://supervisord.org/) if I didn't hear from anybody else...

**Comment by gtfierro** [comment]
I responded to your email, but just in case:

Use systemd if:
- running Ubuntu 16.04
- need to enforce run order dependencies between multiple services

Else, my experience w/ supervisord has been fairly similar.  Supervisord is written in python, though, and systemd is written as an init system, so its a bit more dependable and offers more features. Supervisord has some nice interaction features such as a web UI and the ability to be set as a login shell

**Comment by shankari** [comment]
I don't think that I can (easily) use the web interface to supervisord. The IRB protocol requires that I only open ports 443 and 22. If I want to open anything else, I have to file another amendment, and I don't want to spend another couple of weeks on that.

do either `systemd` or `supervisord` require the process to have a PID file? I'm not sure that bottle does has an option to do that, and I'd probably have to muck with something like:
http://stackoverflow.com/questions/1444790/python-module-for-creating-pid-based-lockfile

**Comment by gtfierro** [comment]
You don't need a web interface for supervisord. There is a command line utility.

Neither require a PID file. They create/fork the process themselves, so they have the PID

**Comment by shankari** [comment]
awesome - will check ubuntu version and then use the appropriate package. Will ping you if I have more questions. Can't take you up on offer to help with setup, alas - IRB protocol currently states that I am the only person who will have access to the main server, since it stores the `email -> UUID` mapping.

**Comment by gtfierro** [comment]
Well, what we can do is you can point me to the bottle application source and I can show you how to create the supervisord/systemd file for that. Its easy enough to install; configuration is really the only "tricky" part and that's straightforward once you've done it once or twice.

**Comment by shankari** [comment]
Thanks so much, @gtfierro. The bottle code and application source are at:
https://github.com/e-mission/e-mission-server/tree/master/emission/net/api
`{bottle.py, cfc_webapp.py}`.

The script that I use the launch the application is:
`./e-mission-py.bash emission/net/api/cfc_webapp.py`

**Comment by gtfierro** [comment]
For supervisord:

```ini
[program:emissionpy]
command=/usr/local/bin/python emission/net/api/cfc_webapp.py
environment=PYTHONPATH="."
directory=/path/to/where/it/is
autostart=true
autorestart=true
stderr_logfile=/var/log/emissionpy.err.log
stdout_logfile=/var/log/emissionpy.out.log
```

For systemd

```ini
[Unit]
Description=emission server

[Service]
Restart=always
RestartSec=30
WorkingDirectory=/path/to/where/it/is
Environment=PYTHONPATH=.
ExecStart =/usr/local/bin/python emission/net/api/cfc_webapp.py

[Install]
WantedBy=multi-user.target
```

Those should work, modulo of the directories being correct. You'll need to look up how to install the files, but that's straightforward. Its also worth reading up on the relative merits of the two systems so you can make an informed judgement on which one to use. I think either should be fine for your purposes.

**Comment by shankari** [comment]
I'm still on Ubuntu 14.04.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```

It doesn't have systemd

```
$ systemctl
systemctl: command not found
```

supervisord it is

**Comment by shankari** [comment]
FYI, the `environment=PYTHONPATH="."` option does not seem to work.

```
$ /home/ubuntu/anaconda/bin/supervisord -n
2016-07-27 09:21:04,957 INFO RPC interface 'supervisor' initialized
2016-07-27 09:21:04,957 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2016-07-27 09:21:04,957 INFO supervisord started with pid 19230
2016-07-27 09:21:05,960 INFO spawned: 'emissionpy' with pid 19233
2016-07-27 09:21:06,265 INFO exited: emissionpy (exit status 1; not expected)
2016-07-27 09:21:07,268 INFO spawned: 'emissionpy' with pid 19237
2016-07-27 09:21:07,451 INFO exited: emissionpy (exit status 1; not expected)
2016-07-27 09:21:09,455 INFO spawned: 'emissionpy' with pid 19241
2016-07-27 09:21:09,638 INFO exited: emissionpy (exit status 1; not expected)
2016-07-27 09:21:12,643 INFO spawned: 'emissionpy' with pid 19245
2016-07-27 09:21:12,830 INFO exited: emissionpy (exit status 1; not expected)
^C2016-07-27 09:21:13,253 INFO gave up: emissionpy entered FATAL state, too many start retries too quickly
2016-07-27 09:21:13,253 WARN received SIGINT indicating exit request
```

Because some modules are not found in spite of the PYTHONPATH.

```
$ less /mnt/logs/emission/emissionpy.err.log
Traceback (most recent call last):
  File "emission/net/api/cfc_webapp.py", line 29, in <module>
    import modeshare, zipcode, distance, tripManager, \
  File "/mnt/e-mission/e-mission-server/emission/net/api/modeshare.py", line 6, in <module>
    from emission.core.common import Is_date, Is_place, get_mode_share_by_distance, berkeley_area, travel_time
ImportError: No module named emission.core.common
ubuntu@ip-10-203-173-119:/mnt/e-mission/e-mission-server$ ls emission/core/common.py
emission/core/common.py

```

Changing it to 

```
command=sudo ./e-mission-py.bash emission/net/api/cfc_webapp.py
```

worked fine. Given the time, I am not going to investigate this further.

Thanks @gtfierro for all the help!

**Comment by shankari** [comment]
Closing this now.
#349 is tracking the longer-term fix.
