### ISSUE TITLE
Check in a script to change client_ts to ts in existing data

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-server#38]
Tonight, I checked in a change to make the stat timestamp less client centric, since the code is now reused for server and result stats as well. But this means that the data will have a mishmash of client_ts and ts fields, which will make analysis challenging.

Check in a migration script that will rename client_ts to ts in the existing data to make it consistent.

**Comment by lechiang** [comment]
mine!!!!!!

**Comment by jeffdh5** [comment]
Here are some lines of code in mongodb console that can achieve this:

use Stage_database
db.Stage_client_stats.update({}, {$rename:{"client_ts":"ts"}}, false, true);

**Comment by shankari** [comment]
testing?

**Comment by jeffdh5** [comment]
Original:
db.Stage_client_stats.find()
{ "_id" : ObjectId("543c8f4688f663587d21cd4e"), "reported_ts" : 1413254982.201671, "stat" : "battery_level", "user" : BinData(3,"+P7iDA8yNZ26dbzpenrIOw=="), "client_os_version" : "4.4.2", "reading" : "4.0", "client_app_version" : "2.0.1", "client_ts" : "1413254944995" }
{ "_id" : ObjectId("543c8f4688f663587d21cd4f"), "reported_ts" : 1413254982.201671, "stat" : "battery_level", "user" : BinData(3,"+P7iDA8yNZ26dbzpenrIOw=="), "client_os_version" : "4.4.2", "reading" : "4.0", "client_app_version" : "2.0.1", "client_ts" : "1413254946390" }
{ "_id" : ObjectId("543c8f4688f663587d21cd50"), "reported_ts" : 1413254982.201671, "stat" : "sync_push_list_size", "user" : BinData(3,"+P7iDA8yNZ26dbzpenrIOw=="), "client_os_version" : "4.4.2", "reading" : "0", "client_app_version" : "2.0.1", "client_ts" : "1413254946390" }
{ "_id" : ObjectId("543c8f4688f663587d21cd51"), "reported_ts" : 1413254982.201671, "stat" : "sync_pull_list_size", "user" : BinData(3,"+P7iDA8yNZ26dbzpenrIOw=="), "client_os_version" : "4.4.2", "reading" : "0", "client_app_version" : "2.0.1", "client_ts" : "1413254946390" }
{ "_id" : ObjectId("543c8f4688f663587d21cd52"), "reported_ts" : 1413254982.201671, "stat" : "confirmlist_ucs_size", "user" : BinData(3,"+P7iDA8yNZ26dbzpenrIOw=="), "client_os_version" : "4.4.2", "reading" : "0", "client_app_version" : "2.0.1", "client_ts" : "1413254944995" }
{ "_id" : ObjectId("543c8f4688f663587d21cd53"), "reported_ts" : 1413254982.201671, "stat" : "confirmlist_resume", "user" : BinData(3,"+P7iDA8yNZ26dbzpenrIOw=="), "client_os_version" : "4.4.2", "reading" : null, "client_app_version" : "2.0.1", "client_ts" : "1413254944995" }
{ "_id" : ObjectId("543c8f4688f663587d21cd54"), "reported_ts" : 1413254982.201671, "stat" : "sync_launched", "user" : BinData(3,"+P7iDA8yNZ26dbzpenrIOw=="), "client_os_version" : "4.4.2", "reading" : null, "client_app_version" : "2.0.1", "client_ts" : "1413254946390" }

After running the above code:

db.Stage_client_stats.find()
{ "_id" : ObjectId("543c8f4688f663587d21cd4e"), "reported_ts" : 1413254982.201671, "stat" : "battery_level", "user" : BinData(3,"+P7iDA8yNZ26dbzpenrIOw=="), "client_os_version" : "4.4.2", "reading" : "4.0", "client_app_version" : "2.0.1", "ts" : "1413254944995" }
{ "_id" : ObjectId("543c8f4688f663587d21cd4f"), "reported_ts" : 1413254982.201671, "stat" : "battery_level", "user" : BinData(3,"+P7iDA8yNZ26dbzpenrIOw=="), "client_os_version" : "4.4.2", "reading" : "4.0", "client_app_version" : "2.0.1", "ts" : "1413254946390" }
{ "_id" : ObjectId("543c8f4688f663587d21cd50"), "reported_ts" : 1413254982.201671, "stat" : "sync_push_list_size", "user" : BinData(3,"+P7iDA8yNZ26dbzpenrIOw=="), "client_os_version" : "4.4.2", "reading" : "0", "client_app_version" : "2.0.1", "ts" : "1413254946390" }
{ "_id" : ObjectId("543c8f4688f663587d21cd51"), "reported_ts" : 1413254982.201671, "stat" : "sync_pull_list_size", "user" : BinData(3,"+P7iDA8yNZ26dbzpenrIOw=="), "client_os_version" : "4.4.2", "reading" : "0", "client_app_version" : "2.0.1", "ts" : "1413254946390" }
{ "_id" : ObjectId("543c8f4688f663587d21cd52"), "reported_ts" : 1413254982.201671, "stat" : "confirmlist_ucs_size", "user" : BinData(3,"+P7iDA8yNZ26dbzpenrIOw=="), "client_os_version" : "4.4.2", "reading" : "0", "client_app_version" : "2.0.1", "ts" : "1413254944995" }
{ "_id" : ObjectId("543c8f4688f663587d21cd53"), "reported_ts" : 1413254982.201671, "stat" : "confirmlist_resume", "user" : BinData(3,"+P7iDA8yNZ26dbzpenrIOw=="), "client_os_version" : "4.4.2", "reading" : null, "client_app_version" : "2.0.1", "ts" : "1413254944995" }

**Comment by shankari** [comment]
Looks good.

In general, when I do migrations like these, I like to have a little script that documents what I changed so that I am not confused later.

Is it possible for you to put that into a little python script using pymongo? It should literally be 4 lines of code - 
    import pymongo
    db = MongoClient().Stage_database.Stage_Sections
...

See examples in `CFC_WebApp/utils/migrations`, and your new script would go in there too.
I will still count that you turned in the assignment on time.

**Comment by jeffdh5** [comment]
We tried PyMongo and couldn't get it to work. I don't have time today to work on it, but I can investigate it tomorrow or over the weekend, if that's okay?

**Comment by shankari** [comment]
That's fine. Let me know if you need help debugging pymongo.
Sending me the error message, or setting up a quick screenshare session can
help you get unblocked.

Thanks,
Shankari

**Comment by shankari** [comment]
@jeffdh5, @lechiang, do you have an ETA on the script? Did you get a chance to investigate pymongo?
A lot of the existing code uses pymongo if you want some examples...

**Comment by jeffdh5** [comment]
Here's the code that we wrote:

from pymongo import MongoClient
client = MongoClient()
db = client.Stage_database
collection = db.Stage_client_stats

collection.update({}, { '$set': {"client_ts": "ts"}}, False, True)

We can't seem to get it to make a change on the database. It definitely open a connection but it doesn't make any update.

**Comment by shankari** [comment]
Isn't there a subtle difference between the query that you ran from the console and the query that you run from the script?

*From the console*
       db.Stage_client_stats.update({}, {$rename:{"client_ts":"ts"}}, false, true);
*From the script*
       db.Stage_client_stats.update({}, {'$set':{"client_ts":"ts"}}, False, True);

Did you try $rename in the script too? Doesn't it work?

**Comment by jeffdh5** [comment]
I've tried both already.

**Comment by shankari** [comment]
Also, I would be careful about just using "False", "True" in python. The full syntax of the update command is:
      update(spec, document[, upsert=False[, manipulate=False[, safe=None[, multi=False[, check_keys=True[, **kwargs]]]]]])
http://api.mongodb.org/python/current/api/pymongo/collection.html#pymongo.collection.Collection.update

So your call should map to upsert=False, manipulate=True. Is that what you wanted? You might want to write them out explicitly to be clear. Also, wouldn't you want multi=True as well?

**Comment by jeffdh5** [comment]
Ah that fixed it.

**Comment by shankari** [comment]
Yeah, RTFM will get you every time :)
Waiting for the pull request...

**Comment by jeffdh5** [comment]
I sent it though, do you not see it?

**Comment by shankari** [comment]
Yeah saw it now.
