### ISSUE TITLE
Store raw sensed data to help in debugging conversion

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-server#48]
We parse the raw data from the phone in the collect method. As we change the raw data format, we need to ensure that the parsing is correct. This is easiest if we have the raw data stored on the server so that we can write tests more easily.

**Comment by jesca** [comment]
we will be working on this !

**Comment by jesca** [comment]
shankari --- it looks like you merged a branch (dumping the raw input data into log_base_dir)  -- is this issue still open?

**Comment by shankari** [comment]
Fixed via #69
