### ISSUE TITLE
Define requirements.txt file to streamline development environment setup

### ISSUE THREAD

**Issue by zacatac** [e-mission/e-mission-server#49]
https://pip.readthedocs.org/en/1.1/requirements.html

**Comment by shankari** [comment]
Can you send me a pull request with the requirements.txt file?
I'm trying to encourage the notion that this is really a shared project and a shared repo.
I'll look things over, but you should feel free to modify things!

**Comment by zacatac** [comment]
Thanks for the comment! Just sent a request https://github.com/e-mission/e-mission-server/pull/50.

**Comment by zacatac** [comment]
Updated the pull request to reflect changes in README that explain how to use the requirements file: #53

**Comment by shankari** [comment]
Pull request has been merged.
