### ISSUE TITLE
testing server connection

### ISSUE THREAD

**Issue by deepalics0044** [e-mission/e-mission-server#587]
So while testing my connection to the server,why really we change server.host to 0.0.0.0?
I changed it and found out after starting the server
Listening on http://0.0.0.0:8080/
Steps are not clear

    change server.host in conf/net/api/webserver.conf to 0.0.0.0, and
    connect the app to the special IP for the current host in the android emulator - 10.0.2.2

**Comment by shankari** [comment]
You change the server host to 0.0.0.0 to tell it to listen to all IPs that are configured on the host.
https://serverfault.com/questions/78048/whats-the-difference-between-ip-address-0-0-0-0-and-127-0-0-1#78058

**Comment by shankari** [comment]
Closing this. Please reopen if you still have questions...
