### ISSUE TITLE
white screen error

### ISSUE THREAD

**Issue by deepalics0044** [e-mission/e-mission-server#588]
![screenshot from 2018-07-13 07-27-10](https://user-images.githubusercontent.com/40918557/42641448-2e34c4a6-8612-11e8-9937-c1b0f01a3dec.png)
After starting the data server and UI server, I couldn't get through the app using 10.0.2.2 .It gives a white screen.

**Comment by shankari** [comment]
Can you clarify what you mean by "couldn't get through the app"?
Please list the exact steps that you used.

**Comment by deepalics0044** [comment]
![screenshot from 2018-07-13 07-39-03](https://user-images.githubusercontent.com/40918557/42642068-a05a2c96-8613-11e8-9c96-cbc7a4f88b7e.png)
![screenshot from 2018-07-13 07-39-43](https://user-images.githubusercontent.com/40918557/42642070-a090eb46-8613-11e8-8b24-e2f26f20eaaa.png)

**Comment by shankari** [comment]
Ah, you are connecting the *UI* to 10.0.0.2.
Note that there are two servers:
- one is used to deploy the UI
- the other is used to collect data

When you first connect, you have not yet downloaded the UI, so you will need to first connect to the UI server (the one started using `npm serve`)

Then when you have finished downloading the UI, it should connect to the server at 10.0.0.2 (it does this by default, IIRC)

**Comment by deepalics0044** [comment]
I tried connecting to the UI server and still I am getting a white screen.

**Comment by shankari** [comment]
Did you try the troubleshooting tips in the docs repository?
https://github.com/e-mission/e-mission-docs/blob/master/docs/overview/high_level_faq.md#i-get-a-blank-screen-while-loading-the-e-mission-phone-ui

**Comment by shankari** [comment]
I think this has been resolved with the workshop; please let me know if not.
