### ISSUE TITLE
Installation page accessibility issues

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-server#600]
Reported by @uwtcat.

@uwtcat, please indicate which of the fields in this installation page need to have improved accessibility, and what the alt-text needs to be for each of them.
https://e-mission.eecs.berkeley.edu/#/client_setup?new_client=opentoall&clear_usercache=true&clear_local_storage=true

<img width="1433" alt="screen shot 2018-09-19 at 4 16 35 pm" src="https://user-images.githubusercontent.com/2423263/45787003-f120b880-bc27-11e8-9436-19895d760097.png">

**Comment by uwtcat** [comment]
The main issues have to do with the div's that contain the step image and step number, as well as any labels for the links.

@alexmooc2 can give you more precise information on where to insert the label, but he has inserted it into the svg tag and this did the trick. For instance, refer to this image:
https://drive.google.com/a/cs.washington.edu/file/d/1yNTAu-fr3Eih7C1YSYvPEMRlEYaxoNoH/view?usp=sharing

**Comment by shankari** [comment]
@alexmooc2, if you give me updates before this weekend, I'll try to get the update merged before then.

**Comment by shankari** [comment]
@alexmooc2 would you like to review the fix? I will plan on merging and deploying tomorrow morning otherwise.

**Comment by alexmooc2** [comment]
@shankari  Looks good. The aria-labels should give screen readers the proper announcements for the graphics.
