### ISSUE TITLE
no socket could be created (port 80)

### ISSUE THREAD

**Issue by ecvick85** [e-mission/e-mission-server#634]
When trying to run the server on port 80, we are receiving this error:

```
./e-mission-py.bash emission/net/api/cfc_webapp.py
storage not configured, falling back to sample, default configuration
Connecting to database URL localhost
Finished configuring logging for <RootLogger root (WARNING)>
Replaced json_dumps in plugin with the one from bson
Changing bt.json_loads from <function <lambda> at 0x7f05f9145400> to <function loads at 0x7f05f5db3f28>
Running with HTTPS turned OFF - use a reverse proxy on production
Bottle v0.13-dev server starting up (using CherootServer())...
Listening on http://52.91.65.149:80/
Hit Ctrl-C to quit.

Traceback (most recent call last):
  File "emission/net/api/cfc_webapp.py", line 504, in <module>
    run(host=server_host, port=server_port, server='cheroot', debug=True)
  File "/home/ubuntu/e-mission-server/emission/net/api/bottle.py", line 3713, in run
    server.run(app)
  File "/home/ubuntu/e-mission-server/emission/net/api/bottle.py", line 3303, in run
    server.start()
  File "/home/ubuntu/miniconda3/envs/emission/lib/python3.6/site-packages/cheroot/server.py", line 1525, in start
    raise socket.error(msg)
OSError: No socket could be created -- (('52.91.65.149', 80): [Errno 99] Cannot assign requested address)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='conf/storage/db.conf.sample' mode='r' encoding='UTF-8'>
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='conf/net/ext_service/habitica.json' mode='r' encoding='UTF-8'>
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='conf/net/ext_service/yelpfusion.json' mode='r' encoding='UTF-8'>
```

Any tips?

**Comment by shankari** [comment]
port 80 is a system port. You cannot open it as a non-root user.

**Comment by shankari** [comment]
https://serverfault.com/questions/112795/how-to-run-a-server-on-port-80-as-a-normal-user-on-linux

**Comment by ecvick85** [comment]
I tried running the server as root and received this error (and I'm in the emission environment too)
```
sudo ./e-mission-py.bash emission/net/api/cfc_webapp.py
sudo: unable to resolve host ip-
Traceback (most recent call last):
  File "emission/net/api/cfc_webapp.py", line 6, in <module>
    from future import standard_library
ImportError: No module named future
```

**Comment by shankari** [comment]
@ecvick85 do you remember what the `no module named future` error represents?
It is very well known :)

**Comment by shankari** [comment]
also, you might want to look up what sudo actually does, including in terms of environment variable propagation.

**Comment by shankari** [comment]
@ecvick85 did you figure this out? If you did not, then instead of doing the pedagogically right thing and helping you figure out the answer, I might just tell you, since we do have to get this to work before the demo to Trevor's professor.

**Comment by ecvick85** [comment]
The server is back up - I don't think I did it the safe way, however. I logged in as root (sudo -s) then I started the emission environment and restarted the server on port 80.

**Comment by shankari** [comment]
@ecvick85 Great job! We were able to do this the pedagogically right way because you figured out the answer yourself :) You are right that it is still not the best overall solution (as the posts on stackoverflow said) but I think it is fine for now.

**Comment by shankari** [comment]
> and restarted the server on port 80.

Doesn't seem to be running on port 80. I just tried connecting to http://52.91.65.149 and it hangs.

**Comment by shankari** [comment]
ah, I had to open port 80 in the incoming port list
I did wonder why the connection hung instead of failing...

**Comment by shankari** [comment]
@ecvick85 if this is resolved, can you please close this bug?
